# Functions
## Practice Problems

### 1. Following the function design recipe, define:
  * a function that converts Fahrenheit into Celsius
  * a function that converts kilometers into miles. (Assume there are 1.6 kilometers in a mile.)

In [20]:
# Your code goes here
def fahrenheit_to_celcius(c_to_f): 
    """converts fahrenheit to celsius"""
 
def kilometers_to_miles(k_to_m): 
"""Converts kilometer to miles"""
print(1.6 kilometer = 1 mile)

SyntaxError: invalid syntax (2527521938.py, line 5)

In [21]:
def kilometers_to_miles(kilometers):
    """Converts a distance from kilometers to miles.

    Args:
        kilometers (float): Distance in kilometers.

    Returns:
        float: Distance in miles.
    """
    miles = kilometers / 1.6
    return miles

### 2. What value is printed in the below code?

In [22]:
answer = 3

def answer_to_everything():
    '''Return the answer to life, the universe, and everything'''
    answer = 42
    return answer
    
answer_to_everything()

print(answer)

3

<details>
  <summary>Answer</summary>

  Answer: 3. The answer variable in our function is locally scoped -- our program cannot access the value 42 from outside of the function, including when we called print(answer).

  Although we called answer_to_everything(), we did not assign the output to a variable.
</details>

### 3. Complete the examples in the docstring below, then write the body of the function. You can assume `num` is always >= 0.

In [25]:
def repeat(string, num):
    ''' Return string repeated num times.
    >>> repeat('yes', 4)
    'yesyesyesyes'
    >>> repeat('no', 0)
    # your expected output here
    >>> repeat('yesnomaybe', 3)
    # your expected output here
    ''' "yesnomaybeyesnomaybeyesnomaybe"
    output = string*num
    return output

### 4. Complete the function below. You can assume that `number` will always be a string with 10 digits and that the first 3 digits will always be the area code.

In [26]:
from pickle import TRUE
def is_416_number(number):
    ''' Check whether the number has a 416 area code.
    >>> is_416_number('(416)-555-5555')
    True
    >>> is_416_number('514 416 5555')
    False
    >>> is_416_number('4165554160')
    True
    '''
    # replace parens w/ nothing
    number = number.replace('(', '')
    number = number.replace(')', '')
    output = number[:3] == '416'
    return output